<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.2 setup script
 * Date: Wed, 23 Dec 2015 13:12:04 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Local Mysql Server [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Local Mysql Server';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '3mmN(4^J[O%mPkIR8NB6n0tW|viP4S4zf{B19D#8fSGkX#';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>